// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Rico <rico@mymakercorner.com>
//
// Every named QMK keycode a stock keyboard does not have, with what its keycap says. DATA ONLY
// -- the code that reads it is in NazgKeycapLegend.cpp.
//
// Written from docs/research_material/short-forms.md, its Behaviour, Host, Board and Firmware
// tables, which hold the rules and the checks behind every word: a header -- what the key acts
// on -- over a main legend -- the action -- each with its short form, both fitting a 1u key at
// the smallest board. Plain committed source, like the keycode and host-layout tables: when QMK
// adds keycodes, extend short-forms.md by its rules and this table with it.
//
// Not here, built in code from their parts: the numbered families (MC_n, JS_n, PB_n, BT_PRFn,
// QK_USER_n, QK_KB_n), Space Cadet -- drawn as tap-hold keys -- and MIDI and steno, which print
// QMK's own name.

#include "NazgKeycapLegend.h"

namespace nazg
{
    namespace
    {
        using C = CommandCategory;

        constexpr CommandEntry c_Commands[] = {
            // Behaviour
            { .key = "AS_DOWN", .category = C::Behaviour, .header = "Auto Shift", .headerShort = "AutoSft", .main = "Time −" },
            { .key = "AS_OFF", .category = C::Behaviour, .header = "Auto Shift", .headerShort = "AutoSft", .main = "Off" },
            { .key = "AS_ON", .category = C::Behaviour, .header = "Auto Shift", .headerShort = "AutoSft", .main = "On" },
            { .key = "AS_RPT", .category = C::Behaviour, .header = "Auto Shift", .headerShort = "AutoSft", .main = "Report", .mainShort = "Rpt" },
            { .key = "AS_TOGG", .category = C::Behaviour, .header = "Auto Shift", .headerShort = "AutoSft", .main = "On/Off" },
            { .key = "AS_UP", .category = C::Behaviour, .header = "Auto Shift", .headerShort = "AutoSft", .main = "Time +" },
            { .key = "AC_OFF", .category = C::Behaviour, .header = "Autocorrect", .headerShort = "AutoCor", .main = "Off" },
            { .key = "AC_ON", .category = C::Behaviour, .header = "Autocorrect", .headerShort = "AutoCor", .main = "On" },
            { .key = "AC_TOGG", .category = C::Behaviour, .header = "Autocorrect", .headerShort = "AutoCor", .main = "On/Off" },
            { .key = "CW_TOGG", .category = C::Behaviour, .header = "Caps Word", .headerShort = "Caps Wd", .main = "On/Off" },
            { .key = "CM_OFF", .category = C::Behaviour, .header = "Combos", .main = "Off" },
            { .key = "CM_ON", .category = C::Behaviour, .header = "Combos", .main = "On" },
            { .key = "CM_TOGG", .category = C::Behaviour, .header = "Combos", .main = "On/Off" },
            { .key = "QK_AREP", .category = C::Behaviour, .header = "Key", .main = "Alt Rep" },
            { .key = "QK_GESC", .category = C::Behaviour, .header = "Key", .main = "Grv Esc" },
            { .key = "QK_LEAD", .category = C::Behaviour, .header = "Key", .main = "Leader", .mainShort = "Lead" },
            { .key = "QK_LOCK", .category = C::Behaviour, .header = "Key", .main = "Lock" },
            { .key = "QK_REP", .category = C::Behaviour, .header = "Key", .main = "Repeat", .mainShort = "Rep" },
            { .key = "QK_LLCK", .category = C::Behaviour, .header = "Layer", .main = "Lock" },
            { .key = "OS_OFF", .category = C::Behaviour, .header = "One shot", .main = "Off" },
            { .key = "OS_ON", .category = C::Behaviour, .header = "One shot", .main = "On" },
            { .key = "OS_TOGG", .category = C::Behaviour, .header = "One shot", .main = "On/Off" },
            { .key = "KO_OFF", .category = C::Behaviour, .header = "Overrides", .headerShort = "Ovrd", .main = "Off" },
            { .key = "KO_ON", .category = C::Behaviour, .header = "Overrides", .headerShort = "Ovrd", .main = "On" },
            { .key = "KO_TOGG", .category = C::Behaviour, .header = "Overrides", .headerShort = "Ovrd", .main = "On/Off" },
            { .key = "SE_LOCK", .category = C::Behaviour, .header = "Secure", .main = "Lock" },
            { .key = "SE_REQ", .category = C::Behaviour, .header = "Secure", .main = "Request", .mainShort = "Req" },
            { .key = "SE_TOGG", .category = C::Behaviour, .header = "Secure", .main = "On/Off" },
            { .key = "SE_UNLK", .category = C::Behaviour, .header = "Secure", .main = "Unlock" },
            { .key = "SH_MOFF", .category = C::Behaviour, .header = "Swap hands", .headerShort = "Swap", .main = "Hold off", .mainShort = "Hold no" },
            { .key = "SH_MON", .category = C::Behaviour, .header = "Swap hands", .headerShort = "Swap", .main = "Hold" },
            { .key = "SH_OFF", .category = C::Behaviour, .header = "Swap hands", .headerShort = "Swap", .main = "Off" },
            { .key = "SH_ON", .category = C::Behaviour, .header = "Swap hands", .headerShort = "Swap", .main = "On" },
            { .key = "SH_OS", .category = C::Behaviour, .header = "Swap hands", .headerShort = "Swap", .main = "Once" },
            { .key = "SH_TOGG", .category = C::Behaviour, .header = "Swap hands", .headerShort = "Swap", .main = "On/Off" },
            { .key = "SH_TT", .category = C::Behaviour, .header = "Swap hands", .headerShort = "Swap", .main = "Tap tog" },
            { .key = "DT_DOWN", .category = C::Behaviour, .header = "Tap term", .main = "−" },
            { .key = "DT_PRNT", .category = C::Behaviour, .header = "Tap term", .main = "Print" },
            { .key = "DT_UP", .category = C::Behaviour, .header = "Tap term", .main = "+" },
            { .key = "TL_LOWR", .category = C::Behaviour, .header = "Tri layer", .main = "Lower" },
            { .key = "TL_UPPR", .category = C::Behaviour, .header = "Tri layer", .main = "Upper" },

            // Host
            { .key = "KC_ASST", .category = C::Host, .header = "App", .main = "Assistant", .mainShort = "Assist" },
            { .key = "KC_CALC", .category = C::Host, .header = "App", .main = "Calc" },
            { .key = "KC_CPNL", .category = C::Host, .header = "App", .main = "Settings", .mainShort = "Setup" },
            { .key = "KC_LPAD", .category = C::Host, .header = "App", .main = "Launchpad", .mainShort = "Launch" },
            { .key = "KC_MAIL", .category = C::Host, .header = "App", .main = "Mail" },
            { .key = "KC_MCTL", .category = C::Host, .header = "App", .main = "Mission Ctrl", .mainShort = "Mission" },
            { .key = "KC_MYCM", .category = C::Host, .header = "App", .main = "Computer", .mainShort = "PC" },
            { .key = "BT_NEXT", .category = C::Host, .header = "Bluetooth", .headerShort = "BT", .main = "Next" },
            { .key = "BT_PREV", .category = C::Host, .header = "Bluetooth", .headerShort = "BT", .main = "Prev" },
            { .key = "BT_UNPR", .category = C::Host, .header = "Bluetooth", .headerShort = "BT", .main = "Unpair" },
            { .key = "DM_PLY1", .category = C::Host, .header = "Macro", .main = "Play 1" },
            { .key = "DM_PLY2", .category = C::Host, .header = "Macro", .main = "Play 2" },
            { .key = "DM_REC1", .category = C::Host, .header = "Macro", .main = "Rec 1" },
            { .key = "DM_REC2", .category = C::Host, .header = "Macro", .main = "Rec 2" },
            { .key = "DM_RSTP", .category = C::Host, .header = "Macro", .main = "Stop" },
            { .key = "KC_EJCT", .category = C::Host, .header = "Media", .main = "Eject" },
            { .key = "KC_MFFD", .category = C::Host, .header = "Media", .main = "Fast Fwd", .mainShort = "FFwd" },
            { .key = "KC_MNXT", .category = C::Host, .header = "Media", .main = "Next" },
            { .key = "KC_MPLY", .category = C::Host, .header = "Media", .main = "Play" },
            { .key = "KC_MPRV", .category = C::Host, .header = "Media", .main = "Prev" },
            { .key = "KC_MRWD", .category = C::Host, .header = "Media", .main = "Rewind", .mainShort = "Rew" },
            { .key = "KC_MSEL", .category = C::Host, .header = "Media", .main = "Select", .mainShort = "Sel" },
            { .key = "KC_MSTP", .category = C::Host, .header = "Media", .main = "Stop" },
            { .key = "KC_MUTE", .category = C::Host, .header = "Media", .main = "Mute" },
            { .key = "KC_VOLD", .category = C::Host, .header = "Media", .main = "Vol −" },
            { .key = "KC_VOLU", .category = C::Host, .header = "Media", .main = "Vol +" },
            { .key = "MS_ACL0", .category = C::Host, .header = "Mouse", .main = "Acc 0" },
            { .key = "MS_ACL1", .category = C::Host, .header = "Mouse", .main = "Acc 1" },
            { .key = "MS_ACL2", .category = C::Host, .header = "Mouse", .main = "Acc 2" },
            { .key = "MS_BTN1", .category = C::Host, .header = "Mouse", .main = "Btn 1" },
            { .key = "MS_BTN2", .category = C::Host, .header = "Mouse", .main = "Btn 2" },
            { .key = "MS_BTN3", .category = C::Host, .header = "Mouse", .main = "Btn 3" },
            { .key = "MS_BTN4", .category = C::Host, .header = "Mouse", .main = "Btn 4" },
            { .key = "MS_BTN5", .category = C::Host, .header = "Mouse", .main = "Btn 5" },
            { .key = "MS_BTN6", .category = C::Host, .header = "Mouse", .main = "Btn 6" },
            { .key = "MS_BTN7", .category = C::Host, .header = "Mouse", .main = "Btn 7" },
            { .key = "MS_BTN8", .category = C::Host, .header = "Mouse", .main = "Btn 8" },
            { .key = "MS_DOWN", .category = C::Host, .header = "Mouse", .main = "Down" },
            { .key = "MS_LEFT", .category = C::Host, .header = "Mouse", .main = "Left" },
            { .key = "MS_RGHT", .category = C::Host, .header = "Mouse", .main = "Right" },
            { .key = "MS_UP", .category = C::Host, .header = "Mouse", .main = "Up" },
            { .key = "MS_WHLD", .category = C::Host, .header = "Mouse", .main = "Wh Dn" },
            { .key = "MS_WHLL", .category = C::Host, .header = "Mouse", .main = "Wh Left", .mainShort = "Wh Lt" },
            { .key = "MS_WHLR", .category = C::Host, .header = "Mouse", .main = "Wh Right", .mainShort = "Wh Rt" },
            { .key = "MS_WHLU", .category = C::Host, .header = "Mouse", .main = "Wh Up" },
            { .key = "OU_2P4G", .category = C::Host, .header = "Output", .main = "2.4 GHz", .mainShort = "2.4G" },
            { .key = "OU_AUTO", .category = C::Host, .header = "Output", .main = "Auto" },
            { .key = "OU_BT", .category = C::Host, .header = "Output", .main = "BT" },
            { .key = "OU_NEXT", .category = C::Host, .header = "Output", .main = "Next" },
            { .key = "OU_NONE", .category = C::Host, .header = "Output", .main = "None" },
            { .key = "OU_PREV", .category = C::Host, .header = "Output", .main = "Prev" },
            { .key = "OU_USB", .category = C::Host, .header = "Output", .main = "USB" },
            { .key = "KC_BRID", .category = C::Host, .header = "Screen", .main = "Bri −" },
            { .key = "KC_BRIU", .category = C::Host, .header = "Screen", .main = "Bri +" },
            { .key = "QK_STENO_BOLT", .category = C::Host, .header = "Steno", .main = "Bolt" },
            { .key = "QK_STENO_COMB", .category = C::Host, .header = "Steno", .main = "Comb" },
            { .key = "QK_STENO_COMB_MAX", .category = C::Host, .header = "Steno", .main = "Comb max" },
            { .key = "QK_STENO_GEMINI", .category = C::Host, .header = "Steno", .main = "Gemini" },
            { .key = "KC_PWR", .category = C::Host, .header = "System", .main = "Power" },
            { .key = "KC_SLEP", .category = C::Host, .header = "System", .main = "Sleep" },
            { .key = "KC_WAKE", .category = C::Host, .header = "System", .main = "Wake" },
            { .key = "UC_BSD", .category = C::Host, .header = "Unicode", .main = "BSD" },
            { .key = "UC_EMAC", .category = C::Host, .header = "Unicode", .main = "Emacs" },
            { .key = "UC_LINX", .category = C::Host, .header = "Unicode", .main = "Linux" },
            { .key = "UC_MAC", .category = C::Host, .header = "Unicode", .main = "macOS" },
            { .key = "UC_NEXT", .category = C::Host, .header = "Unicode", .main = "Next" },
            { .key = "UC_PREV", .category = C::Host, .header = "Unicode", .main = "Prev" },
            { .key = "UC_WIN", .category = C::Host, .header = "Unicode", .main = "Windows", .mainShort = "Win" },
            { .key = "UC_WINC", .category = C::Host, .header = "Unicode", .main = "WinCompose", .mainShort = "WinC" },
            { .key = "KC_WBAK", .category = C::Host, .header = "Web", .main = "Back" },
            { .key = "KC_WFAV", .category = C::Host, .header = "Web", .main = "Favorites", .mainShort = "Favs" },
            { .key = "KC_WFWD", .category = C::Host, .header = "Web", .main = "Forward", .mainShort = "Fwd" },
            { .key = "KC_WHOM", .category = C::Host, .header = "Web", .main = "Home" },
            { .key = "KC_WREF", .category = C::Host, .header = "Web", .main = "Refresh", .mainShort = "Refr" },
            { .key = "KC_WSCH", .category = C::Host, .header = "Web", .main = "Search", .mainShort = "Srch" },
            { .key = "KC_WSTP", .category = C::Host, .header = "Web", .main = "Stop" },

            // Board
            { .key = "AU_NEXT", .category = C::Board, .header = "Audio", .main = "Voice +" },
            { .key = "AU_OFF", .category = C::Board, .header = "Audio", .main = "Off" },
            { .key = "AU_ON", .category = C::Board, .header = "Audio", .main = "On" },
            { .key = "AU_PREV", .category = C::Board, .header = "Audio", .main = "Voice −" },
            { .key = "AU_TOGG", .category = C::Board, .header = "Audio", .main = "On/Off" },
            { .key = "CL_CAPS", .category = C::Board, .header = "Caps", .main = "Is Caps" },
            { .key = "CL_CTRL", .category = C::Board, .header = "Caps", .main = "Is Ctrl" },
            { .key = "CK_DOWN", .category = C::Board, .header = "Clicky", .main = "Freq −" },
            { .key = "CK_OFF", .category = C::Board, .header = "Clicky", .main = "Off" },
            { .key = "CK_ON", .category = C::Board, .header = "Clicky", .main = "On" },
            { .key = "CK_RST", .category = C::Board, .header = "Clicky", .main = "Reset" },
            { .key = "CK_TOGG", .category = C::Board, .header = "Clicky", .main = "On/Off" },
            { .key = "CK_UP", .category = C::Board, .header = "Clicky", .main = "Freq +" },
            { .key = "CL_NORM", .category = C::Board, .header = "Ctrl↔Caps", .headerShort = "Ctl/Caps", .main = "Unswap" },
            { .key = "CL_SWAP", .category = C::Board, .header = "Ctrl↔Caps", .headerShort = "Ctl/Caps", .main = "Swap" },
            { .key = "CL_TOGG", .category = C::Board, .header = "Ctrl↔Caps", .headerShort = "Ctl/Caps", .main = "On/Off" },
            { .key = "CG_LNRM", .category = C::Board, .header = "Ctrl↔{GUI}", .headerShort = "Ctl/{GUI}", .main = "Unswap L" },
            { .key = "CG_LSWP", .category = C::Board, .header = "Ctrl↔{GUI}", .headerShort = "Ctl/{GUI}", .main = "Swap L" },
            { .key = "CG_NORM", .category = C::Board, .header = "Ctrl↔{GUI}", .headerShort = "Ctl/{GUI}", .main = "Unswap" },
            { .key = "CG_RNRM", .category = C::Board, .header = "Ctrl↔{GUI}", .headerShort = "Ctl/{GUI}", .main = "Unswap R" },
            { .key = "CG_RSWP", .category = C::Board, .header = "Ctrl↔{GUI}", .headerShort = "Ctl/{GUI}", .main = "Swap R" },
            { .key = "CG_SWAP", .category = C::Board, .header = "Ctrl↔{GUI}", .headerShort = "Ctl/{GUI}", .main = "Swap" },
            { .key = "CG_TOGG", .category = C::Board, .header = "Ctrl↔{GUI}", .headerShort = "Ctl/{GUI}", .main = "On/Off" },
            { .key = "EH_LEFT", .category = C::Board, .header = "EE Hands", .headerShort = "Hands", .main = "Left" },
            { .key = "EH_RGHT", .category = C::Board, .header = "EE Hands", .headerShort = "Hands", .main = "Right" },
            { .key = "EC_NORM", .category = C::Board, .header = "Esc↔Caps", .headerShort = "Esc/Caps", .main = "Unswap" },
            { .key = "EC_SWAP", .category = C::Board, .header = "Esc↔Caps", .headerShort = "Esc/Caps", .main = "Swap" },
            { .key = "EC_TOGG", .category = C::Board, .header = "Esc↔Caps", .headerShort = "Esc/Caps", .main = "On/Off" },
            { .key = "HF_BUZZ", .category = C::Board, .header = "Haptic", .main = "Buzz" },
            { .key = "HF_COND", .category = C::Board, .header = "Haptic", .main = "Cont −" },
            { .key = "HF_CONT", .category = C::Board, .header = "Haptic", .main = "Cont" },
            { .key = "HF_CONU", .category = C::Board, .header = "Haptic", .main = "Cont +" },
            { .key = "HF_DWLD", .category = C::Board, .header = "Haptic", .main = "Dwell −" },
            { .key = "HF_DWLU", .category = C::Board, .header = "Haptic", .main = "Dwell +" },
            { .key = "HF_FDBK", .category = C::Board, .header = "Haptic", .main = "Fdbk" },
            { .key = "HF_NEXT", .category = C::Board, .header = "Haptic", .main = "Next" },
            { .key = "HF_OFF", .category = C::Board, .header = "Haptic", .main = "Off" },
            { .key = "HF_ON", .category = C::Board, .header = "Haptic", .main = "On" },
            { .key = "HF_PREV", .category = C::Board, .header = "Haptic", .main = "Prev" },
            { .key = "HF_RST", .category = C::Board, .header = "Haptic", .main = "Reset" },
            { .key = "HF_TOGG", .category = C::Board, .header = "Haptic", .main = "On/Off" },
            { .key = "BL_BRTG", .category = C::Board, .header = "Light", .main = "Breathe", .system = LightingSystem::Backlight },
            { .key = "BL_DOWN", .category = C::Board, .header = "Light", .main = "Bri −", .system = LightingSystem::Backlight },
            { .key = "BL_OFF", .category = C::Board, .header = "Light", .main = "Off", .system = LightingSystem::Backlight },
            { .key = "BL_ON", .category = C::Board, .header = "Light", .main = "On", .system = LightingSystem::Backlight },
            { .key = "BL_STEP", .category = C::Board, .header = "Light", .main = "Step", .system = LightingSystem::Backlight },
            { .key = "BL_TOGG", .category = C::Board, .header = "Light", .main = "On/Off", .system = LightingSystem::Backlight },
            { .key = "BL_UP", .category = C::Board, .header = "Light", .main = "Bri +", .system = LightingSystem::Backlight },
            { .key = "LM_BRID", .category = C::Board, .header = "Light", .main = "Bri −", .system = LightingSystem::LedMatrix },
            { .key = "LM_BRIU", .category = C::Board, .header = "Light", .main = "Bri +", .system = LightingSystem::LedMatrix },
            { .key = "LM_FLGN", .category = C::Board, .header = "Light", .main = "Flag next", .system = LightingSystem::LedMatrix },
            { .key = "LM_FLGP", .category = C::Board, .header = "Light", .main = "Flag prev", .system = LightingSystem::LedMatrix },
            { .key = "LM_NEXT", .category = C::Board, .header = "Light", .main = "Next", .system = LightingSystem::LedMatrix },
            { .key = "LM_OFF", .category = C::Board, .header = "Light", .main = "Off", .system = LightingSystem::LedMatrix },
            { .key = "LM_ON", .category = C::Board, .header = "Light", .main = "On", .system = LightingSystem::LedMatrix },
            { .key = "LM_PREV", .category = C::Board, .header = "Light", .main = "Prev", .system = LightingSystem::LedMatrix },
            { .key = "LM_SPDD", .category = C::Board, .header = "Light", .main = "Spd −", .system = LightingSystem::LedMatrix },
            { .key = "LM_SPDU", .category = C::Board, .header = "Light", .main = "Spd +", .system = LightingSystem::LedMatrix },
            { .key = "LM_TOGG", .category = C::Board, .header = "Light", .main = "On/Off", .system = LightingSystem::LedMatrix },
            { .key = "RGB_M_B", .category = C::Board, .header = "Light", .main = "Breathe", .system = LightingSystem::Underglow },
            { .key = "RGB_M_G", .category = C::Board, .header = "Light", .main = "Gradient", .mainShort = "Grad", .system = LightingSystem::Underglow },
            { .key = "RGB_M_K", .category = C::Board, .header = "Light", .main = "Knight", .system = LightingSystem::Underglow },
            { .key = "RGB_M_P", .category = C::Board, .header = "Light", .main = "Plain", .system = LightingSystem::Underglow },
            { .key = "RGB_M_R", .category = C::Board, .header = "Light", .main = "Rainbow", .mainShort = "Rainbw", .system = LightingSystem::Underglow },
            { .key = "RGB_M_SN", .category = C::Board, .header = "Light", .main = "Snake", .system = LightingSystem::Underglow },
            { .key = "RGB_M_SW", .category = C::Board, .header = "Light", .main = "Swirl", .system = LightingSystem::Underglow },
            { .key = "RGB_M_T", .category = C::Board, .header = "Light", .main = "Test", .system = LightingSystem::Underglow },
            { .key = "RGB_M_TW", .category = C::Board, .header = "Light", .main = "Twinkle", .system = LightingSystem::Underglow },
            { .key = "RGB_M_X", .category = C::Board, .header = "Light", .main = "Xmas", .system = LightingSystem::Underglow },
            { .key = "RM_FLGN", .category = C::Board, .header = "Light", .main = "Flag next", .system = LightingSystem::RgbMatrix },
            { .key = "RM_FLGP", .category = C::Board, .header = "Light", .main = "Flag prev", .system = LightingSystem::RgbMatrix },
            { .key = "RM_HUED", .category = C::Board, .header = "Light", .main = "Hue −", .system = LightingSystem::RgbMatrix },
            { .key = "RM_HUEU", .category = C::Board, .header = "Light", .main = "Hue +", .system = LightingSystem::RgbMatrix },
            { .key = "RM_NEXT", .category = C::Board, .header = "Light", .main = "Next", .system = LightingSystem::RgbMatrix },
            { .key = "RM_OFF", .category = C::Board, .header = "Light", .main = "Off", .system = LightingSystem::RgbMatrix },
            { .key = "RM_ON", .category = C::Board, .header = "Light", .main = "On", .system = LightingSystem::RgbMatrix },
            { .key = "RM_PREV", .category = C::Board, .header = "Light", .main = "Prev", .system = LightingSystem::RgbMatrix },
            { .key = "RM_SATD", .category = C::Board, .header = "Light", .main = "Sat −", .system = LightingSystem::RgbMatrix },
            { .key = "RM_SATU", .category = C::Board, .header = "Light", .main = "Sat +", .system = LightingSystem::RgbMatrix },
            { .key = "RM_SPDD", .category = C::Board, .header = "Light", .main = "Spd −", .system = LightingSystem::RgbMatrix },
            { .key = "RM_SPDU", .category = C::Board, .header = "Light", .main = "Spd +", .system = LightingSystem::RgbMatrix },
            { .key = "RM_TOGG", .category = C::Board, .header = "Light", .main = "On/Off", .system = LightingSystem::RgbMatrix },
            { .key = "RM_VALD", .category = C::Board, .header = "Light", .main = "Bri −", .system = LightingSystem::RgbMatrix },
            { .key = "RM_VALU", .category = C::Board, .header = "Light", .main = "Bri +", .system = LightingSystem::RgbMatrix },
            { .key = "UG_HUED", .category = C::Board, .header = "Light", .main = "Hue −", .system = LightingSystem::Underglow },
            { .key = "UG_HUEU", .category = C::Board, .header = "Light", .main = "Hue +", .system = LightingSystem::Underglow },
            { .key = "UG_NEXT", .category = C::Board, .header = "Light", .main = "Next", .system = LightingSystem::Underglow },
            { .key = "UG_PREV", .category = C::Board, .header = "Light", .main = "Prev", .system = LightingSystem::Underglow },
            { .key = "UG_SATD", .category = C::Board, .header = "Light", .main = "Sat −", .system = LightingSystem::Underglow },
            { .key = "UG_SATU", .category = C::Board, .header = "Light", .main = "Sat +", .system = LightingSystem::Underglow },
            { .key = "UG_SPDD", .category = C::Board, .header = "Light", .main = "Spd −", .system = LightingSystem::Underglow },
            { .key = "UG_SPDU", .category = C::Board, .header = "Light", .main = "Spd +", .system = LightingSystem::Underglow },
            { .key = "UG_TOGG", .category = C::Board, .header = "Light", .main = "On/Off", .system = LightingSystem::Underglow },
            { .key = "UG_VALD", .category = C::Board, .header = "Light", .main = "Bri −", .system = LightingSystem::Underglow },
            { .key = "UG_VALU", .category = C::Board, .header = "Light", .main = "Bri +", .system = LightingSystem::Underglow },
            { .key = "MU_NEXT", .category = C::Board, .header = "Music", .main = "Mode +" },
            { .key = "MU_OFF", .category = C::Board, .header = "Music", .main = "Off" },
            { .key = "MU_ON", .category = C::Board, .header = "Music", .main = "On" },
            { .key = "MU_TOGG", .category = C::Board, .header = "Music", .main = "On/Off" },
            { .key = "NK_OFF", .category = C::Board, .header = "NKRO", .main = "Off" },
            { .key = "NK_ON", .category = C::Board, .header = "NKRO", .main = "On" },
            { .key = "NK_TOGG", .category = C::Board, .header = "NKRO", .main = "On/Off" },
            { .key = "SQ_OFF", .category = C::Board, .header = "Seq", .main = "Off" },
            { .key = "SQ_ON", .category = C::Board, .header = "Seq", .main = "On" },
            { .key = "SQ_RESD", .category = C::Board, .header = "Seq", .main = "Res −" },
            { .key = "SQ_RESU", .category = C::Board, .header = "Seq", .main = "Res +" },
            { .key = "SQ_SALL", .category = C::Board, .header = "Seq", .main = "All" },
            { .key = "SQ_SCLR", .category = C::Board, .header = "Seq", .main = "Clear" },
            { .key = "SQ_TMPD", .category = C::Board, .header = "Seq", .main = "Tempo −", .mainShort = "BPM −" },
            { .key = "SQ_TMPU", .category = C::Board, .header = "Seq", .main = "Tempo +", .mainShort = "BPM +" },
            { .key = "SQ_TOGG", .category = C::Board, .header = "Seq", .main = "On/Off" },
            { .key = "VK_TOGG", .category = C::Board, .header = "Velocikey", .headerShort = "VelKey", .main = "On/Off" },
            { .key = "BS_NORM", .category = C::Board, .header = "\\↔Bksp", .headerShort = "\\/Bksp", .main = "Unswap" },
            { .key = "BS_SWAP", .category = C::Board, .header = "\\↔Bksp", .headerShort = "\\/Bksp", .main = "Swap" },
            { .key = "BS_TOGG", .category = C::Board, .header = "\\↔Bksp", .headerShort = "\\/Bksp", .main = "On/Off" },
            { .key = "GE_NORM", .category = C::Board, .header = "`↔Esc", .headerShort = "`/Esc", .main = "Unswap" },
            { .key = "GE_SWAP", .category = C::Board, .header = "`↔Esc", .headerShort = "`/Esc", .main = "Swap" },
            { .key = "AG_LNRM", .category = C::Board, .header = "{ALT}↔{GUI}", .headerShort = "{ALTS}/{GUI}", .main = "Unswap L" },
            { .key = "AG_LSWP", .category = C::Board, .header = "{ALT}↔{GUI}", .headerShort = "{ALTS}/{GUI}", .main = "Swap L" },
            { .key = "AG_NORM", .category = C::Board, .header = "{ALT}↔{GUI}", .headerShort = "{ALTS}/{GUI}", .main = "Unswap" },
            { .key = "AG_RNRM", .category = C::Board, .header = "{ALT}↔{GUI}", .headerShort = "{ALTS}/{GUI}", .main = "Unswap R" },
            { .key = "AG_RSWP", .category = C::Board, .header = "{ALT}↔{GUI}", .headerShort = "{ALTS}/{GUI}", .main = "Swap R" },
            { .key = "AG_SWAP", .category = C::Board, .header = "{ALT}↔{GUI}", .headerShort = "{ALTS}/{GUI}", .main = "Swap" },
            { .key = "AG_TOGG", .category = C::Board, .header = "{ALT}↔{GUI}", .headerShort = "{ALTS}/{GUI}", .main = "On/Off" },
            { .key = "GU_OFF", .category = C::Board, .header = "{GUI} key", .headerShort = "{GUI}", .main = "Off" },
            { .key = "GU_ON", .category = C::Board, .header = "{GUI} key", .headerShort = "{GUI}", .main = "On" },
            { .key = "GU_TOGG", .category = C::Board, .header = "{GUI} key", .headerShort = "{GUI}", .main = "On/Off" },

            // Firmware
            { .key = "DB_TOGG", .category = C::Firmware, .header = "Firmware", .main = "Debug" },
            { .key = "EE_CLR", .category = C::Firmware, .header = "Firmware", .main = "Clear EE" },
            { .key = "QK_BOOT", .category = C::Firmware, .header = "Firmware", .main = "Boot" },
            { .key = "QK_MAKE", .category = C::Firmware, .header = "Firmware", .main = "Make" },
            { .key = "QK_RBT", .category = C::Firmware, .header = "Firmware", .main = "Reboot" },
        };
    }

    std::span<const CommandEntry> CommandEntries() noexcept
    {
        return c_Commands;
    }
}
