// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Rico <rico@mymakercorner.com>
//
// Every Latin letter Unicode decomposes into a base letter and one combining accent -- what a
// dead key then a letter compose (ui/NazgHostTyping.h). Generated from Python's unicodedata
// (Unicode 16.0.0), U+00C0 to U+024F and U+1E00 to U+1EFF; regenerated by hand,
// keycodes.md, "Regenerating the host layouts". Sorted by the composed letter.

#include "NazgHostTyping.h"

namespace nazg
{
    namespace
    {
        constexpr Composition c_Compositions[] = {
            { 0x00C0, 0x0041, 0x0300 },   // À Latin Capital Letter A With Grave
            { 0x00C1, 0x0041, 0x0301 },   // Á Latin Capital Letter A With Acute
            { 0x00C2, 0x0041, 0x0302 },   // Â Latin Capital Letter A With Circumflex
            { 0x00C3, 0x0041, 0x0303 },   // Ã Latin Capital Letter A With Tilde
            { 0x00C4, 0x0041, 0x0308 },   // Ä Latin Capital Letter A With Diaeresis
            { 0x00C5, 0x0041, 0x030A },   // Å Latin Capital Letter A With Ring Above
            { 0x00C7, 0x0043, 0x0327 },   // Ç Latin Capital Letter C With Cedilla
            { 0x00C8, 0x0045, 0x0300 },   // È Latin Capital Letter E With Grave
            { 0x00C9, 0x0045, 0x0301 },   // É Latin Capital Letter E With Acute
            { 0x00CA, 0x0045, 0x0302 },   // Ê Latin Capital Letter E With Circumflex
            { 0x00CB, 0x0045, 0x0308 },   // Ë Latin Capital Letter E With Diaeresis
            { 0x00CC, 0x0049, 0x0300 },   // Ì Latin Capital Letter I With Grave
            { 0x00CD, 0x0049, 0x0301 },   // Í Latin Capital Letter I With Acute
            { 0x00CE, 0x0049, 0x0302 },   // Î Latin Capital Letter I With Circumflex
            { 0x00CF, 0x0049, 0x0308 },   // Ï Latin Capital Letter I With Diaeresis
            { 0x00D1, 0x004E, 0x0303 },   // Ñ Latin Capital Letter N With Tilde
            { 0x00D2, 0x004F, 0x0300 },   // Ò Latin Capital Letter O With Grave
            { 0x00D3, 0x004F, 0x0301 },   // Ó Latin Capital Letter O With Acute
            { 0x00D4, 0x004F, 0x0302 },   // Ô Latin Capital Letter O With Circumflex
            { 0x00D5, 0x004F, 0x0303 },   // Õ Latin Capital Letter O With Tilde
            { 0x00D6, 0x004F, 0x0308 },   // Ö Latin Capital Letter O With Diaeresis
            { 0x00D9, 0x0055, 0x0300 },   // Ù Latin Capital Letter U With Grave
            { 0x00DA, 0x0055, 0x0301 },   // Ú Latin Capital Letter U With Acute
            { 0x00DB, 0x0055, 0x0302 },   // Û Latin Capital Letter U With Circumflex
            { 0x00DC, 0x0055, 0x0308 },   // Ü Latin Capital Letter U With Diaeresis
            { 0x00DD, 0x0059, 0x0301 },   // Ý Latin Capital Letter Y With Acute
            { 0x00E0, 0x0061, 0x0300 },   // à Latin Small Letter A With Grave
            { 0x00E1, 0x0061, 0x0301 },   // á Latin Small Letter A With Acute
            { 0x00E2, 0x0061, 0x0302 },   // â Latin Small Letter A With Circumflex
            { 0x00E3, 0x0061, 0x0303 },   // ã Latin Small Letter A With Tilde
            { 0x00E4, 0x0061, 0x0308 },   // ä Latin Small Letter A With Diaeresis
            { 0x00E5, 0x0061, 0x030A },   // å Latin Small Letter A With Ring Above
            { 0x00E7, 0x0063, 0x0327 },   // ç Latin Small Letter C With Cedilla
            { 0x00E8, 0x0065, 0x0300 },   // è Latin Small Letter E With Grave
            { 0x00E9, 0x0065, 0x0301 },   // é Latin Small Letter E With Acute
            { 0x00EA, 0x0065, 0x0302 },   // ê Latin Small Letter E With Circumflex
            { 0x00EB, 0x0065, 0x0308 },   // ë Latin Small Letter E With Diaeresis
            { 0x00EC, 0x0069, 0x0300 },   // ì Latin Small Letter I With Grave
            { 0x00ED, 0x0069, 0x0301 },   // í Latin Small Letter I With Acute
            { 0x00EE, 0x0069, 0x0302 },   // î Latin Small Letter I With Circumflex
            { 0x00EF, 0x0069, 0x0308 },   // ï Latin Small Letter I With Diaeresis
            { 0x00F1, 0x006E, 0x0303 },   // ñ Latin Small Letter N With Tilde
            { 0x00F2, 0x006F, 0x0300 },   // ò Latin Small Letter O With Grave
            { 0x00F3, 0x006F, 0x0301 },   // ó Latin Small Letter O With Acute
            { 0x00F4, 0x006F, 0x0302 },   // ô Latin Small Letter O With Circumflex
            { 0x00F5, 0x006F, 0x0303 },   // õ Latin Small Letter O With Tilde
            { 0x00F6, 0x006F, 0x0308 },   // ö Latin Small Letter O With Diaeresis
            { 0x00F9, 0x0075, 0x0300 },   // ù Latin Small Letter U With Grave
            { 0x00FA, 0x0075, 0x0301 },   // ú Latin Small Letter U With Acute
            { 0x00FB, 0x0075, 0x0302 },   // û Latin Small Letter U With Circumflex
            { 0x00FC, 0x0075, 0x0308 },   // ü Latin Small Letter U With Diaeresis
            { 0x00FD, 0x0079, 0x0301 },   // ý Latin Small Letter Y With Acute
            { 0x00FF, 0x0079, 0x0308 },   // ÿ Latin Small Letter Y With Diaeresis
            { 0x0100, 0x0041, 0x0304 },   // Ā Latin Capital Letter A With Macron
            { 0x0101, 0x0061, 0x0304 },   // ā Latin Small Letter A With Macron
            { 0x0102, 0x0041, 0x0306 },   // Ă Latin Capital Letter A With Breve
            { 0x0103, 0x0061, 0x0306 },   // ă Latin Small Letter A With Breve
            { 0x0104, 0x0041, 0x0328 },   // Ą Latin Capital Letter A With Ogonek
            { 0x0105, 0x0061, 0x0328 },   // ą Latin Small Letter A With Ogonek
            { 0x0106, 0x0043, 0x0301 },   // Ć Latin Capital Letter C With Acute
            { 0x0107, 0x0063, 0x0301 },   // ć Latin Small Letter C With Acute
            { 0x0108, 0x0043, 0x0302 },   // Ĉ Latin Capital Letter C With Circumflex
            { 0x0109, 0x0063, 0x0302 },   // ĉ Latin Small Letter C With Circumflex
            { 0x010A, 0x0043, 0x0307 },   // Ċ Latin Capital Letter C With Dot Above
            { 0x010B, 0x0063, 0x0307 },   // ċ Latin Small Letter C With Dot Above
            { 0x010C, 0x0043, 0x030C },   // Č Latin Capital Letter C With Caron
            { 0x010D, 0x0063, 0x030C },   // č Latin Small Letter C With Caron
            { 0x010E, 0x0044, 0x030C },   // Ď Latin Capital Letter D With Caron
            { 0x010F, 0x0064, 0x030C },   // ď Latin Small Letter D With Caron
            { 0x0112, 0x0045, 0x0304 },   // Ē Latin Capital Letter E With Macron
            { 0x0113, 0x0065, 0x0304 },   // ē Latin Small Letter E With Macron
            { 0x0114, 0x0045, 0x0306 },   // Ĕ Latin Capital Letter E With Breve
            { 0x0115, 0x0065, 0x0306 },   // ĕ Latin Small Letter E With Breve
            { 0x0116, 0x0045, 0x0307 },   // Ė Latin Capital Letter E With Dot Above
            { 0x0117, 0x0065, 0x0307 },   // ė Latin Small Letter E With Dot Above
            { 0x0118, 0x0045, 0x0328 },   // Ę Latin Capital Letter E With Ogonek
            { 0x0119, 0x0065, 0x0328 },   // ę Latin Small Letter E With Ogonek
            { 0x011A, 0x0045, 0x030C },   // Ě Latin Capital Letter E With Caron
            { 0x011B, 0x0065, 0x030C },   // ě Latin Small Letter E With Caron
            { 0x011C, 0x0047, 0x0302 },   // Ĝ Latin Capital Letter G With Circumflex
            { 0x011D, 0x0067, 0x0302 },   // ĝ Latin Small Letter G With Circumflex
            { 0x011E, 0x0047, 0x0306 },   // Ğ Latin Capital Letter G With Breve
            { 0x011F, 0x0067, 0x0306 },   // ğ Latin Small Letter G With Breve
            { 0x0120, 0x0047, 0x0307 },   // Ġ Latin Capital Letter G With Dot Above
            { 0x0121, 0x0067, 0x0307 },   // ġ Latin Small Letter G With Dot Above
            { 0x0122, 0x0047, 0x0327 },   // Ģ Latin Capital Letter G With Cedilla
            { 0x0123, 0x0067, 0x0327 },   // ģ Latin Small Letter G With Cedilla
            { 0x0124, 0x0048, 0x0302 },   // Ĥ Latin Capital Letter H With Circumflex
            { 0x0125, 0x0068, 0x0302 },   // ĥ Latin Small Letter H With Circumflex
            { 0x0128, 0x0049, 0x0303 },   // Ĩ Latin Capital Letter I With Tilde
            { 0x0129, 0x0069, 0x0303 },   // ĩ Latin Small Letter I With Tilde
            { 0x012A, 0x0049, 0x0304 },   // Ī Latin Capital Letter I With Macron
            { 0x012B, 0x0069, 0x0304 },   // ī Latin Small Letter I With Macron
            { 0x012C, 0x0049, 0x0306 },   // Ĭ Latin Capital Letter I With Breve
            { 0x012D, 0x0069, 0x0306 },   // ĭ Latin Small Letter I With Breve
            { 0x012E, 0x0049, 0x0328 },   // Į Latin Capital Letter I With Ogonek
            { 0x012F, 0x0069, 0x0328 },   // į Latin Small Letter I With Ogonek
            { 0x0130, 0x0049, 0x0307 },   // İ Latin Capital Letter I With Dot Above
            { 0x0134, 0x004A, 0x0302 },   // Ĵ Latin Capital Letter J With Circumflex
            { 0x0135, 0x006A, 0x0302 },   // ĵ Latin Small Letter J With Circumflex
            { 0x0136, 0x004B, 0x0327 },   // Ķ Latin Capital Letter K With Cedilla
            { 0x0137, 0x006B, 0x0327 },   // ķ Latin Small Letter K With Cedilla
            { 0x0139, 0x004C, 0x0301 },   // Ĺ Latin Capital Letter L With Acute
            { 0x013A, 0x006C, 0x0301 },   // ĺ Latin Small Letter L With Acute
            { 0x013B, 0x004C, 0x0327 },   // Ļ Latin Capital Letter L With Cedilla
            { 0x013C, 0x006C, 0x0327 },   // ļ Latin Small Letter L With Cedilla
            { 0x013D, 0x004C, 0x030C },   // Ľ Latin Capital Letter L With Caron
            { 0x013E, 0x006C, 0x030C },   // ľ Latin Small Letter L With Caron
            { 0x0143, 0x004E, 0x0301 },   // Ń Latin Capital Letter N With Acute
            { 0x0144, 0x006E, 0x0301 },   // ń Latin Small Letter N With Acute
            { 0x0145, 0x004E, 0x0327 },   // Ņ Latin Capital Letter N With Cedilla
            { 0x0146, 0x006E, 0x0327 },   // ņ Latin Small Letter N With Cedilla
            { 0x0147, 0x004E, 0x030C },   // Ň Latin Capital Letter N With Caron
            { 0x0148, 0x006E, 0x030C },   // ň Latin Small Letter N With Caron
            { 0x014C, 0x004F, 0x0304 },   // Ō Latin Capital Letter O With Macron
            { 0x014D, 0x006F, 0x0304 },   // ō Latin Small Letter O With Macron
            { 0x014E, 0x004F, 0x0306 },   // Ŏ Latin Capital Letter O With Breve
            { 0x014F, 0x006F, 0x0306 },   // ŏ Latin Small Letter O With Breve
            { 0x0150, 0x004F, 0x030B },   // Ő Latin Capital Letter O With Double Acute
            { 0x0151, 0x006F, 0x030B },   // ő Latin Small Letter O With Double Acute
            { 0x0154, 0x0052, 0x0301 },   // Ŕ Latin Capital Letter R With Acute
            { 0x0155, 0x0072, 0x0301 },   // ŕ Latin Small Letter R With Acute
            { 0x0156, 0x0052, 0x0327 },   // Ŗ Latin Capital Letter R With Cedilla
            { 0x0157, 0x0072, 0x0327 },   // ŗ Latin Small Letter R With Cedilla
            { 0x0158, 0x0052, 0x030C },   // Ř Latin Capital Letter R With Caron
            { 0x0159, 0x0072, 0x030C },   // ř Latin Small Letter R With Caron
            { 0x015A, 0x0053, 0x0301 },   // Ś Latin Capital Letter S With Acute
            { 0x015B, 0x0073, 0x0301 },   // ś Latin Small Letter S With Acute
            { 0x015C, 0x0053, 0x0302 },   // Ŝ Latin Capital Letter S With Circumflex
            { 0x015D, 0x0073, 0x0302 },   // ŝ Latin Small Letter S With Circumflex
            { 0x015E, 0x0053, 0x0327 },   // Ş Latin Capital Letter S With Cedilla
            { 0x015F, 0x0073, 0x0327 },   // ş Latin Small Letter S With Cedilla
            { 0x0160, 0x0053, 0x030C },   // Š Latin Capital Letter S With Caron
            { 0x0161, 0x0073, 0x030C },   // š Latin Small Letter S With Caron
            { 0x0162, 0x0054, 0x0327 },   // Ţ Latin Capital Letter T With Cedilla
            { 0x0163, 0x0074, 0x0327 },   // ţ Latin Small Letter T With Cedilla
            { 0x0164, 0x0054, 0x030C },   // Ť Latin Capital Letter T With Caron
            { 0x0165, 0x0074, 0x030C },   // ť Latin Small Letter T With Caron
            { 0x0168, 0x0055, 0x0303 },   // Ũ Latin Capital Letter U With Tilde
            { 0x0169, 0x0075, 0x0303 },   // ũ Latin Small Letter U With Tilde
            { 0x016A, 0x0055, 0x0304 },   // Ū Latin Capital Letter U With Macron
            { 0x016B, 0x0075, 0x0304 },   // ū Latin Small Letter U With Macron
            { 0x016C, 0x0055, 0x0306 },   // Ŭ Latin Capital Letter U With Breve
            { 0x016D, 0x0075, 0x0306 },   // ŭ Latin Small Letter U With Breve
            { 0x016E, 0x0055, 0x030A },   // Ů Latin Capital Letter U With Ring Above
            { 0x016F, 0x0075, 0x030A },   // ů Latin Small Letter U With Ring Above
            { 0x0170, 0x0055, 0x030B },   // Ű Latin Capital Letter U With Double Acute
            { 0x0171, 0x0075, 0x030B },   // ű Latin Small Letter U With Double Acute
            { 0x0172, 0x0055, 0x0328 },   // Ų Latin Capital Letter U With Ogonek
            { 0x0173, 0x0075, 0x0328 },   // ų Latin Small Letter U With Ogonek
            { 0x0174, 0x0057, 0x0302 },   // Ŵ Latin Capital Letter W With Circumflex
            { 0x0175, 0x0077, 0x0302 },   // ŵ Latin Small Letter W With Circumflex
            { 0x0176, 0x0059, 0x0302 },   // Ŷ Latin Capital Letter Y With Circumflex
            { 0x0177, 0x0079, 0x0302 },   // ŷ Latin Small Letter Y With Circumflex
            { 0x0178, 0x0059, 0x0308 },   // Ÿ Latin Capital Letter Y With Diaeresis
            { 0x0179, 0x005A, 0x0301 },   // Ź Latin Capital Letter Z With Acute
            { 0x017A, 0x007A, 0x0301 },   // ź Latin Small Letter Z With Acute
            { 0x017B, 0x005A, 0x0307 },   // Ż Latin Capital Letter Z With Dot Above
            { 0x017C, 0x007A, 0x0307 },   // ż Latin Small Letter Z With Dot Above
            { 0x017D, 0x005A, 0x030C },   // Ž Latin Capital Letter Z With Caron
            { 0x017E, 0x007A, 0x030C },   // ž Latin Small Letter Z With Caron
            { 0x01A0, 0x004F, 0x031B },   // Ơ Latin Capital Letter O With Horn
            { 0x01A1, 0x006F, 0x031B },   // ơ Latin Small Letter O With Horn
            { 0x01AF, 0x0055, 0x031B },   // Ư Latin Capital Letter U With Horn
            { 0x01B0, 0x0075, 0x031B },   // ư Latin Small Letter U With Horn
            { 0x01CD, 0x0041, 0x030C },   // Ǎ Latin Capital Letter A With Caron
            { 0x01CE, 0x0061, 0x030C },   // ǎ Latin Small Letter A With Caron
            { 0x01CF, 0x0049, 0x030C },   // Ǐ Latin Capital Letter I With Caron
            { 0x01D0, 0x0069, 0x030C },   // ǐ Latin Small Letter I With Caron
            { 0x01D1, 0x004F, 0x030C },   // Ǒ Latin Capital Letter O With Caron
            { 0x01D2, 0x006F, 0x030C },   // ǒ Latin Small Letter O With Caron
            { 0x01D3, 0x0055, 0x030C },   // Ǔ Latin Capital Letter U With Caron
            { 0x01D4, 0x0075, 0x030C },   // ǔ Latin Small Letter U With Caron
            { 0x01E2, 0x00C6, 0x0304 },   // Ǣ Latin Capital Letter Ae With Macron
            { 0x01E3, 0x00E6, 0x0304 },   // ǣ Latin Small Letter Ae With Macron
            { 0x01E6, 0x0047, 0x030C },   // Ǧ Latin Capital Letter G With Caron
            { 0x01E7, 0x0067, 0x030C },   // ǧ Latin Small Letter G With Caron
            { 0x01E8, 0x004B, 0x030C },   // Ǩ Latin Capital Letter K With Caron
            { 0x01E9, 0x006B, 0x030C },   // ǩ Latin Small Letter K With Caron
            { 0x01EA, 0x004F, 0x0328 },   // Ǫ Latin Capital Letter O With Ogonek
            { 0x01EB, 0x006F, 0x0328 },   // ǫ Latin Small Letter O With Ogonek
            { 0x01EE, 0x01B7, 0x030C },   // Ǯ Latin Capital Letter Ezh With Caron
            { 0x01EF, 0x0292, 0x030C },   // ǯ Latin Small Letter Ezh With Caron
            { 0x01F0, 0x006A, 0x030C },   // ǰ Latin Small Letter J With Caron
            { 0x01F4, 0x0047, 0x0301 },   // Ǵ Latin Capital Letter G With Acute
            { 0x01F5, 0x0067, 0x0301 },   // ǵ Latin Small Letter G With Acute
            { 0x01F8, 0x004E, 0x0300 },   // Ǹ Latin Capital Letter N With Grave
            { 0x01F9, 0x006E, 0x0300 },   // ǹ Latin Small Letter N With Grave
            { 0x01FC, 0x00C6, 0x0301 },   // Ǽ Latin Capital Letter Ae With Acute
            { 0x01FD, 0x00E6, 0x0301 },   // ǽ Latin Small Letter Ae With Acute
            { 0x01FE, 0x00D8, 0x0301 },   // Ǿ Latin Capital Letter O With Stroke And Acute
            { 0x01FF, 0x00F8, 0x0301 },   // ǿ Latin Small Letter O With Stroke And Acute
            { 0x0200, 0x0041, 0x030F },   // Ȁ Latin Capital Letter A With Double Grave
            { 0x0201, 0x0061, 0x030F },   // ȁ Latin Small Letter A With Double Grave
            { 0x0202, 0x0041, 0x0311 },   // Ȃ Latin Capital Letter A With Inverted Breve
            { 0x0203, 0x0061, 0x0311 },   // ȃ Latin Small Letter A With Inverted Breve
            { 0x0204, 0x0045, 0x030F },   // Ȅ Latin Capital Letter E With Double Grave
            { 0x0205, 0x0065, 0x030F },   // ȅ Latin Small Letter E With Double Grave
            { 0x0206, 0x0045, 0x0311 },   // Ȇ Latin Capital Letter E With Inverted Breve
            { 0x0207, 0x0065, 0x0311 },   // ȇ Latin Small Letter E With Inverted Breve
            { 0x0208, 0x0049, 0x030F },   // Ȉ Latin Capital Letter I With Double Grave
            { 0x0209, 0x0069, 0x030F },   // ȉ Latin Small Letter I With Double Grave
            { 0x020A, 0x0049, 0x0311 },   // Ȋ Latin Capital Letter I With Inverted Breve
            { 0x020B, 0x0069, 0x0311 },   // ȋ Latin Small Letter I With Inverted Breve
            { 0x020C, 0x004F, 0x030F },   // Ȍ Latin Capital Letter O With Double Grave
            { 0x020D, 0x006F, 0x030F },   // ȍ Latin Small Letter O With Double Grave
            { 0x020E, 0x004F, 0x0311 },   // Ȏ Latin Capital Letter O With Inverted Breve
            { 0x020F, 0x006F, 0x0311 },   // ȏ Latin Small Letter O With Inverted Breve
            { 0x0210, 0x0052, 0x030F },   // Ȑ Latin Capital Letter R With Double Grave
            { 0x0211, 0x0072, 0x030F },   // ȑ Latin Small Letter R With Double Grave
            { 0x0212, 0x0052, 0x0311 },   // Ȓ Latin Capital Letter R With Inverted Breve
            { 0x0213, 0x0072, 0x0311 },   // ȓ Latin Small Letter R With Inverted Breve
            { 0x0214, 0x0055, 0x030F },   // Ȕ Latin Capital Letter U With Double Grave
            { 0x0215, 0x0075, 0x030F },   // ȕ Latin Small Letter U With Double Grave
            { 0x0216, 0x0055, 0x0311 },   // Ȗ Latin Capital Letter U With Inverted Breve
            { 0x0217, 0x0075, 0x0311 },   // ȗ Latin Small Letter U With Inverted Breve
            { 0x0218, 0x0053, 0x0326 },   // Ș Latin Capital Letter S With Comma Below
            { 0x0219, 0x0073, 0x0326 },   // ș Latin Small Letter S With Comma Below
            { 0x021A, 0x0054, 0x0326 },   // Ț Latin Capital Letter T With Comma Below
            { 0x021B, 0x0074, 0x0326 },   // ț Latin Small Letter T With Comma Below
            { 0x021E, 0x0048, 0x030C },   // Ȟ Latin Capital Letter H With Caron
            { 0x021F, 0x0068, 0x030C },   // ȟ Latin Small Letter H With Caron
            { 0x0226, 0x0041, 0x0307 },   // Ȧ Latin Capital Letter A With Dot Above
            { 0x0227, 0x0061, 0x0307 },   // ȧ Latin Small Letter A With Dot Above
            { 0x0228, 0x0045, 0x0327 },   // Ȩ Latin Capital Letter E With Cedilla
            { 0x0229, 0x0065, 0x0327 },   // ȩ Latin Small Letter E With Cedilla
            { 0x022E, 0x004F, 0x0307 },   // Ȯ Latin Capital Letter O With Dot Above
            { 0x022F, 0x006F, 0x0307 },   // ȯ Latin Small Letter O With Dot Above
            { 0x0232, 0x0059, 0x0304 },   // Ȳ Latin Capital Letter Y With Macron
            { 0x0233, 0x0079, 0x0304 },   // ȳ Latin Small Letter Y With Macron
            { 0x1E00, 0x0041, 0x0325 },   // Ḁ Latin Capital Letter A With Ring Below
            { 0x1E01, 0x0061, 0x0325 },   // ḁ Latin Small Letter A With Ring Below
            { 0x1E02, 0x0042, 0x0307 },   // Ḃ Latin Capital Letter B With Dot Above
            { 0x1E03, 0x0062, 0x0307 },   // ḃ Latin Small Letter B With Dot Above
            { 0x1E04, 0x0042, 0x0323 },   // Ḅ Latin Capital Letter B With Dot Below
            { 0x1E05, 0x0062, 0x0323 },   // ḅ Latin Small Letter B With Dot Below
            { 0x1E06, 0x0042, 0x0331 },   // Ḇ Latin Capital Letter B With Line Below
            { 0x1E07, 0x0062, 0x0331 },   // ḇ Latin Small Letter B With Line Below
            { 0x1E0A, 0x0044, 0x0307 },   // Ḋ Latin Capital Letter D With Dot Above
            { 0x1E0B, 0x0064, 0x0307 },   // ḋ Latin Small Letter D With Dot Above
            { 0x1E0C, 0x0044, 0x0323 },   // Ḍ Latin Capital Letter D With Dot Below
            { 0x1E0D, 0x0064, 0x0323 },   // ḍ Latin Small Letter D With Dot Below
            { 0x1E0E, 0x0044, 0x0331 },   // Ḏ Latin Capital Letter D With Line Below
            { 0x1E0F, 0x0064, 0x0331 },   // ḏ Latin Small Letter D With Line Below
            { 0x1E10, 0x0044, 0x0327 },   // Ḑ Latin Capital Letter D With Cedilla
            { 0x1E11, 0x0064, 0x0327 },   // ḑ Latin Small Letter D With Cedilla
            { 0x1E12, 0x0044, 0x032D },   // Ḓ Latin Capital Letter D With Circumflex Below
            { 0x1E13, 0x0064, 0x032D },   // ḓ Latin Small Letter D With Circumflex Below
            { 0x1E18, 0x0045, 0x032D },   // Ḙ Latin Capital Letter E With Circumflex Below
            { 0x1E19, 0x0065, 0x032D },   // ḙ Latin Small Letter E With Circumflex Below
            { 0x1E1A, 0x0045, 0x0330 },   // Ḛ Latin Capital Letter E With Tilde Below
            { 0x1E1B, 0x0065, 0x0330 },   // ḛ Latin Small Letter E With Tilde Below
            { 0x1E1E, 0x0046, 0x0307 },   // Ḟ Latin Capital Letter F With Dot Above
            { 0x1E1F, 0x0066, 0x0307 },   // ḟ Latin Small Letter F With Dot Above
            { 0x1E20, 0x0047, 0x0304 },   // Ḡ Latin Capital Letter G With Macron
            { 0x1E21, 0x0067, 0x0304 },   // ḡ Latin Small Letter G With Macron
            { 0x1E22, 0x0048, 0x0307 },   // Ḣ Latin Capital Letter H With Dot Above
            { 0x1E23, 0x0068, 0x0307 },   // ḣ Latin Small Letter H With Dot Above
            { 0x1E24, 0x0048, 0x0323 },   // Ḥ Latin Capital Letter H With Dot Below
            { 0x1E25, 0x0068, 0x0323 },   // ḥ Latin Small Letter H With Dot Below
            { 0x1E26, 0x0048, 0x0308 },   // Ḧ Latin Capital Letter H With Diaeresis
            { 0x1E27, 0x0068, 0x0308 },   // ḧ Latin Small Letter H With Diaeresis
            { 0x1E28, 0x0048, 0x0327 },   // Ḩ Latin Capital Letter H With Cedilla
            { 0x1E29, 0x0068, 0x0327 },   // ḩ Latin Small Letter H With Cedilla
            { 0x1E2A, 0x0048, 0x032E },   // Ḫ Latin Capital Letter H With Breve Below
            { 0x1E2B, 0x0068, 0x032E },   // ḫ Latin Small Letter H With Breve Below
            { 0x1E2C, 0x0049, 0x0330 },   // Ḭ Latin Capital Letter I With Tilde Below
            { 0x1E2D, 0x0069, 0x0330 },   // ḭ Latin Small Letter I With Tilde Below
            { 0x1E30, 0x004B, 0x0301 },   // Ḱ Latin Capital Letter K With Acute
            { 0x1E31, 0x006B, 0x0301 },   // ḱ Latin Small Letter K With Acute
            { 0x1E32, 0x004B, 0x0323 },   // Ḳ Latin Capital Letter K With Dot Below
            { 0x1E33, 0x006B, 0x0323 },   // ḳ Latin Small Letter K With Dot Below
            { 0x1E34, 0x004B, 0x0331 },   // Ḵ Latin Capital Letter K With Line Below
            { 0x1E35, 0x006B, 0x0331 },   // ḵ Latin Small Letter K With Line Below
            { 0x1E36, 0x004C, 0x0323 },   // Ḷ Latin Capital Letter L With Dot Below
            { 0x1E37, 0x006C, 0x0323 },   // ḷ Latin Small Letter L With Dot Below
            { 0x1E3A, 0x004C, 0x0331 },   // Ḻ Latin Capital Letter L With Line Below
            { 0x1E3B, 0x006C, 0x0331 },   // ḻ Latin Small Letter L With Line Below
            { 0x1E3C, 0x004C, 0x032D },   // Ḽ Latin Capital Letter L With Circumflex Below
            { 0x1E3D, 0x006C, 0x032D },   // ḽ Latin Small Letter L With Circumflex Below
            { 0x1E3E, 0x004D, 0x0301 },   // Ḿ Latin Capital Letter M With Acute
            { 0x1E3F, 0x006D, 0x0301 },   // ḿ Latin Small Letter M With Acute
            { 0x1E40, 0x004D, 0x0307 },   // Ṁ Latin Capital Letter M With Dot Above
            { 0x1E41, 0x006D, 0x0307 },   // ṁ Latin Small Letter M With Dot Above
            { 0x1E42, 0x004D, 0x0323 },   // Ṃ Latin Capital Letter M With Dot Below
            { 0x1E43, 0x006D, 0x0323 },   // ṃ Latin Small Letter M With Dot Below
            { 0x1E44, 0x004E, 0x0307 },   // Ṅ Latin Capital Letter N With Dot Above
            { 0x1E45, 0x006E, 0x0307 },   // ṅ Latin Small Letter N With Dot Above
            { 0x1E46, 0x004E, 0x0323 },   // Ṇ Latin Capital Letter N With Dot Below
            { 0x1E47, 0x006E, 0x0323 },   // ṇ Latin Small Letter N With Dot Below
            { 0x1E48, 0x004E, 0x0331 },   // Ṉ Latin Capital Letter N With Line Below
            { 0x1E49, 0x006E, 0x0331 },   // ṉ Latin Small Letter N With Line Below
            { 0x1E4A, 0x004E, 0x032D },   // Ṋ Latin Capital Letter N With Circumflex Below
            { 0x1E4B, 0x006E, 0x032D },   // ṋ Latin Small Letter N With Circumflex Below
            { 0x1E54, 0x0050, 0x0301 },   // Ṕ Latin Capital Letter P With Acute
            { 0x1E55, 0x0070, 0x0301 },   // ṕ Latin Small Letter P With Acute
            { 0x1E56, 0x0050, 0x0307 },   // Ṗ Latin Capital Letter P With Dot Above
            { 0x1E57, 0x0070, 0x0307 },   // ṗ Latin Small Letter P With Dot Above
            { 0x1E58, 0x0052, 0x0307 },   // Ṙ Latin Capital Letter R With Dot Above
            { 0x1E59, 0x0072, 0x0307 },   // ṙ Latin Small Letter R With Dot Above
            { 0x1E5A, 0x0052, 0x0323 },   // Ṛ Latin Capital Letter R With Dot Below
            { 0x1E5B, 0x0072, 0x0323 },   // ṛ Latin Small Letter R With Dot Below
            { 0x1E5E, 0x0052, 0x0331 },   // Ṟ Latin Capital Letter R With Line Below
            { 0x1E5F, 0x0072, 0x0331 },   // ṟ Latin Small Letter R With Line Below
            { 0x1E60, 0x0053, 0x0307 },   // Ṡ Latin Capital Letter S With Dot Above
            { 0x1E61, 0x0073, 0x0307 },   // ṡ Latin Small Letter S With Dot Above
            { 0x1E62, 0x0053, 0x0323 },   // Ṣ Latin Capital Letter S With Dot Below
            { 0x1E63, 0x0073, 0x0323 },   // ṣ Latin Small Letter S With Dot Below
            { 0x1E6A, 0x0054, 0x0307 },   // Ṫ Latin Capital Letter T With Dot Above
            { 0x1E6B, 0x0074, 0x0307 },   // ṫ Latin Small Letter T With Dot Above
            { 0x1E6C, 0x0054, 0x0323 },   // Ṭ Latin Capital Letter T With Dot Below
            { 0x1E6D, 0x0074, 0x0323 },   // ṭ Latin Small Letter T With Dot Below
            { 0x1E6E, 0x0054, 0x0331 },   // Ṯ Latin Capital Letter T With Line Below
            { 0x1E6F, 0x0074, 0x0331 },   // ṯ Latin Small Letter T With Line Below
            { 0x1E70, 0x0054, 0x032D },   // Ṱ Latin Capital Letter T With Circumflex Below
            { 0x1E71, 0x0074, 0x032D },   // ṱ Latin Small Letter T With Circumflex Below
            { 0x1E72, 0x0055, 0x0324 },   // Ṳ Latin Capital Letter U With Diaeresis Below
            { 0x1E73, 0x0075, 0x0324 },   // ṳ Latin Small Letter U With Diaeresis Below
            { 0x1E74, 0x0055, 0x0330 },   // Ṵ Latin Capital Letter U With Tilde Below
            { 0x1E75, 0x0075, 0x0330 },   // ṵ Latin Small Letter U With Tilde Below
            { 0x1E76, 0x0055, 0x032D },   // Ṷ Latin Capital Letter U With Circumflex Below
            { 0x1E77, 0x0075, 0x032D },   // ṷ Latin Small Letter U With Circumflex Below
            { 0x1E7C, 0x0056, 0x0303 },   // Ṽ Latin Capital Letter V With Tilde
            { 0x1E7D, 0x0076, 0x0303 },   // ṽ Latin Small Letter V With Tilde
            { 0x1E7E, 0x0056, 0x0323 },   // Ṿ Latin Capital Letter V With Dot Below
            { 0x1E7F, 0x0076, 0x0323 },   // ṿ Latin Small Letter V With Dot Below
            { 0x1E80, 0x0057, 0x0300 },   // Ẁ Latin Capital Letter W With Grave
            { 0x1E81, 0x0077, 0x0300 },   // ẁ Latin Small Letter W With Grave
            { 0x1E82, 0x0057, 0x0301 },   // Ẃ Latin Capital Letter W With Acute
            { 0x1E83, 0x0077, 0x0301 },   // ẃ Latin Small Letter W With Acute
            { 0x1E84, 0x0057, 0x0308 },   // Ẅ Latin Capital Letter W With Diaeresis
            { 0x1E85, 0x0077, 0x0308 },   // ẅ Latin Small Letter W With Diaeresis
            { 0x1E86, 0x0057, 0x0307 },   // Ẇ Latin Capital Letter W With Dot Above
            { 0x1E87, 0x0077, 0x0307 },   // ẇ Latin Small Letter W With Dot Above
            { 0x1E88, 0x0057, 0x0323 },   // Ẉ Latin Capital Letter W With Dot Below
            { 0x1E89, 0x0077, 0x0323 },   // ẉ Latin Small Letter W With Dot Below
            { 0x1E8A, 0x0058, 0x0307 },   // Ẋ Latin Capital Letter X With Dot Above
            { 0x1E8B, 0x0078, 0x0307 },   // ẋ Latin Small Letter X With Dot Above
            { 0x1E8C, 0x0058, 0x0308 },   // Ẍ Latin Capital Letter X With Diaeresis
            { 0x1E8D, 0x0078, 0x0308 },   // ẍ Latin Small Letter X With Diaeresis
            { 0x1E8E, 0x0059, 0x0307 },   // Ẏ Latin Capital Letter Y With Dot Above
            { 0x1E8F, 0x0079, 0x0307 },   // ẏ Latin Small Letter Y With Dot Above
            { 0x1E90, 0x005A, 0x0302 },   // Ẑ Latin Capital Letter Z With Circumflex
            { 0x1E91, 0x007A, 0x0302 },   // ẑ Latin Small Letter Z With Circumflex
            { 0x1E92, 0x005A, 0x0323 },   // Ẓ Latin Capital Letter Z With Dot Below
            { 0x1E93, 0x007A, 0x0323 },   // ẓ Latin Small Letter Z With Dot Below
            { 0x1E94, 0x005A, 0x0331 },   // Ẕ Latin Capital Letter Z With Line Below
            { 0x1E95, 0x007A, 0x0331 },   // ẕ Latin Small Letter Z With Line Below
            { 0x1E96, 0x0068, 0x0331 },   // ẖ Latin Small Letter H With Line Below
            { 0x1E97, 0x0074, 0x0308 },   // ẗ Latin Small Letter T With Diaeresis
            { 0x1E98, 0x0077, 0x030A },   // ẘ Latin Small Letter W With Ring Above
            { 0x1E99, 0x0079, 0x030A },   // ẙ Latin Small Letter Y With Ring Above
            { 0x1E9B, 0x017F, 0x0307 },   // ẛ Latin Small Letter Long S With Dot Above
            { 0x1EA0, 0x0041, 0x0323 },   // Ạ Latin Capital Letter A With Dot Below
            { 0x1EA1, 0x0061, 0x0323 },   // ạ Latin Small Letter A With Dot Below
            { 0x1EA2, 0x0041, 0x0309 },   // Ả Latin Capital Letter A With Hook Above
            { 0x1EA3, 0x0061, 0x0309 },   // ả Latin Small Letter A With Hook Above
            { 0x1EB8, 0x0045, 0x0323 },   // Ẹ Latin Capital Letter E With Dot Below
            { 0x1EB9, 0x0065, 0x0323 },   // ẹ Latin Small Letter E With Dot Below
            { 0x1EBA, 0x0045, 0x0309 },   // Ẻ Latin Capital Letter E With Hook Above
            { 0x1EBB, 0x0065, 0x0309 },   // ẻ Latin Small Letter E With Hook Above
            { 0x1EBC, 0x0045, 0x0303 },   // Ẽ Latin Capital Letter E With Tilde
            { 0x1EBD, 0x0065, 0x0303 },   // ẽ Latin Small Letter E With Tilde
            { 0x1EC8, 0x0049, 0x0309 },   // Ỉ Latin Capital Letter I With Hook Above
            { 0x1EC9, 0x0069, 0x0309 },   // ỉ Latin Small Letter I With Hook Above
            { 0x1ECA, 0x0049, 0x0323 },   // Ị Latin Capital Letter I With Dot Below
            { 0x1ECB, 0x0069, 0x0323 },   // ị Latin Small Letter I With Dot Below
            { 0x1ECC, 0x004F, 0x0323 },   // Ọ Latin Capital Letter O With Dot Below
            { 0x1ECD, 0x006F, 0x0323 },   // ọ Latin Small Letter O With Dot Below
            { 0x1ECE, 0x004F, 0x0309 },   // Ỏ Latin Capital Letter O With Hook Above
            { 0x1ECF, 0x006F, 0x0309 },   // ỏ Latin Small Letter O With Hook Above
            { 0x1EE4, 0x0055, 0x0323 },   // Ụ Latin Capital Letter U With Dot Below
            { 0x1EE5, 0x0075, 0x0323 },   // ụ Latin Small Letter U With Dot Below
            { 0x1EE6, 0x0055, 0x0309 },   // Ủ Latin Capital Letter U With Hook Above
            { 0x1EE7, 0x0075, 0x0309 },   // ủ Latin Small Letter U With Hook Above
            { 0x1EF2, 0x0059, 0x0300 },   // Ỳ Latin Capital Letter Y With Grave
            { 0x1EF3, 0x0079, 0x0300 },   // ỳ Latin Small Letter Y With Grave
            { 0x1EF4, 0x0059, 0x0323 },   // Ỵ Latin Capital Letter Y With Dot Below
            { 0x1EF5, 0x0079, 0x0323 },   // ỵ Latin Small Letter Y With Dot Below
            { 0x1EF6, 0x0059, 0x0309 },   // Ỷ Latin Capital Letter Y With Hook Above
            { 0x1EF7, 0x0079, 0x0309 },   // ỷ Latin Small Letter Y With Hook Above
            { 0x1EF8, 0x0059, 0x0303 },   // Ỹ Latin Capital Letter Y With Tilde
            { 0x1EF9, 0x0079, 0x0303 },   // ỹ Latin Small Letter Y With Tilde
        };
    }

    std::span<const Composition> Compositions() noexcept
    {
        return c_Compositions;
    }
}
